version: '3'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - fn-dash-db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    command: python manage.py runserver
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/usr/share/fn-dash

  redis:
    restart: always
    image: redis
    volumes:
      - fn-dash-redis:/data

  celery:
    restart: always
    command: /bin/sh util/docker.celery.sh
    build:
      context: .
      dockerfile: DockerfileCelery
    volumes:
      - .:/usr/share/fn-dash
    depends_on:
      - postgres
      - redis

volumes:
  fn-dash-db:
  fn-dash-redis: