version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fndash-dev
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/DockerFile
    image: fn-dash
    command: python manage.py runserver
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/usr/share/fn-dash

  redis:
    image: redis
    volumes:
      - redis:/data

  celery:
    build:
      context: .
      dockerfile: docker/DockerFile
    image: fn-dash
    command: sh docker/docker.celery.sh
    volumes:
      - .:/usr/share/fn-dash
    depends_on:
      - postgres
      - redis
  
  upgrade:
    build:
      context: .
      dockerfile: docker/DockerFile
    image: fn-dash
    command: bash -c 'while ! nc -q 1 postgres 5432 </dev/null; do sleep 1; done && flask db upgrade'
    environment:
      - FLASK_APP=manage.py
    volumes:
      - .:/usr/share/fn-dash
    links:
      - postgres

volumes:
  db:
  redis: