version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fndash
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis

  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: fn-dash-prod
    restart: always
    command: gunicorn -w 4 -b :5000 --log-level debug manage:app
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
      - APP_NAME=prod
    ports:
      - 5000:5000
    depends_on:
      - postgres

  celery:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: fn-dash-prod
    restart: always
    command: sh docker/docker.celery.sh
    environment:
      - APP_NAME=prod
    depends_on:
      - redis
      - postgres
  
  upgrade:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: fn-dash-prod
    command: bash -c 'while ! nc -q 1 postgres 5432 </dev/null; do sleep 1; done && flask db upgrade'
    environment:
      - FLASK_APP=manage.py
    depends_on:
      - postgres

volumes:
  db: