version: '3'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - fn-dash-db:/var/lib/postgresql/data

  app:
    build: app
    restart: always
    command: python manage.py runserver
    environment:
      - FLASK_APP=manage.py
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/share/fn-dash/app
      - /usr/share/fn-dash/app/static/foundation-sites-6.5.1

  worker:
    build: worker
    restart: always
    command: python -u worker.py
    depends_on:
      - postgres
    volumes:
      - ./worker:/usr/share/fn-dash/worker

volumes:
  fn-dash-db: