version: '3'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fndash
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: fndash
        awslogs-stream: postgres

  app:
    build:
      context: .
      dockerfile: docker/DockerFileProd
    image: fn-dash-prod
    restart: always
    command: gunicorn -w 4 -b :5000 --log-level debug manage:app
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
    ports:
      - 5000:5000
    depends_on:
      - postgres
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: fndash
        awslogs-stream: app

  redis:
    restart: always
    image: redis
    volumes:
      - redis:/data
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: fndash
        awslogs-stream: redis

  celery:
    build:
      context: .
      dockerfile: docker/DockerFileProd
    image: fn-dash-prod
    restart: always
    command: sh docker/docker.celery.sh
    depends_on:
      - postgres
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: fndash
        awslogs-stream: celery
  
  upgrade:
    build:
      context: .
      dockerfile: docker/DockerFileProd
    image: fn-dash-prod
    command: bash -c 'while ! nc -q 1 postgres 5432 </dev/null; do sleep 1; done && flask db upgrade'
    environment:
      - FLASK_APP=manage.py
    links:
      - postgres
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: fndash
        awslogs-stream: upgrade

volumes:
  db:
  redis: